### ISSUE TITLE
error ValueError: time data 'ET TIMESTAMP=15' does not match format '%y%m%d %H:%M:%S'

### ISSUE THREAD

**Issue by sbwfnhn** [mercos/mysql-binlog-explorer#24]
[root@localhost data]# pip install mysql-binlog-explorer
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: mysql-binlog-explorer in /usr/lib/python2.7/site-packages (0.2.4)
Requirement already satisfied: bottle==0.12.17 in /usr/lib/python2.7/site-packages (from mysql-binlog-explorer) (0.12.17)
Requirement already satisfied: simplejson==3.13.2 in /usr/lib64/python2.7/site-packages (from mysql-binlog-explorer) (3.13.2)
[root@localhost data]# mysql-binlog-explorer my-bin-log.txt
Parsing my-bin-log.txt...
Traceback (most recent call last):
  File "/usr/bin/mysql-binlog-explorer", line 9, in <module>
    load_entry_point('mysql-binlog-explorer==0.2.4', 'console_scripts', 'mysql-binlog-explorer')()
  File "/usr/lib/python2.7/site-packages/binlogexplorer/webui.py", line 98, in main
    transactions += parser.parse(content)
  File "/usr/lib/python2.7/site-packages/binlogexplorer/binlog_parser.py", line 63, in parse
    transaction.end_date = datetime.strptime(last_line[1:16], '%y%m%d %H:%M:%S')
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'ET TIMESTAMP=15' does not match format '%y%m%d %H:%M:%S'

**Comment by sbwfnhn** [comment]
my-bin-log.txt

# at 3232
#191224 11:38:04 server id 2236393393  end_log_pos 3263 CRC32 0xc2123116        Xid = 23
COMMIT/*!*/;
# at 3263
#191224 11:38:04 server id 2236393393  end_log_pos 3311 CRC32 0x86861a2b        GTID [commit=yes]
SET @@SESSION.GTID_NEXT= '7946dcf1-8638-11e7-836c-7cd30abda78a:4953767'/*!*/;
# at 3311
#191224 11:38:04 server id 2236393393  end_log_pos 3374 CRC32 0xb05fec09        Query   thread_id=6065117       exec_time=0     error_code=0
SET TIMESTAMP=1577158684/*!*/;
BEGIN
/*!*/;
# at 3374
#191224 11:38:04 server id 2236393393  end_log_pos 3505 CRC32 0xd0348d29        Table_map: `coralglobal_no1`.`withdrawal` mapped to number 72
# at 3505
#191224 11:38:04 server id 2236393393  end_log_pos 3753 CRC32 0xf999a2c0        Write_rows: table id 72 flags: STMT_END_F
### INSERT INTO `coralglobal_no1`.`withdrawal`
### SET
###   @1='19122411380405636' /* VARSTRING(63) meta=63 nullable=0 is_null=0 */
###   @2='19082409555401696' /* VARSTRING(90) meta=90 nullable=0 is_null=0 */

**Comment by sbwfnhn** [comment]
# at 3232
#191224 11:38:04 server id 2236393393  end_log_pos 3263 CRC32 0xc2123116        Xid = 23
COMMIT/*!*/;
# at 3263
#191224 11:38:04 server id 2236393393  end_log_pos 3311 CRC32 0x86861a2b        GTID [commit=yes]
SET @@SESSION.GTID_NEXT= '7946dcf1-8638-11e7-836c-7cd30abda78a:4953767'/*!*/;
# at 3311
#191224 11:38:04 server id 2236393393  end_log_pos 3374 CRC32 0xb05fec09        Query   thread_id=6065117       exec_time=0     error_code=0
SET TIMESTAMP=1577158684/*!*/;
BEGIN
/*!*/;
# at 3374
#191224 11:38:04 server id 2236393393  end_log_pos 3505 CRC32 0xd0348d29        Table_map: `ccccccc`.`fffffffff` mapped to number 72
# at 3505
#191224 11:38:04 server id 2236393393  end_log_pos 3753 CRC32 0xf999a2c0        Write_rows: table id 72 flags: STMT_END_F
### INSERT INTO `cccccc`.`fffffffff`
### SET
###   @1='19122411380405636' /* VARSTRING(63) meta=63 nullable=0 is_null=0 */
###   @2='19082409555401696' /* VARSTRING(90) meta=90 nullable=0 is_null=0 */

**Comment by sbwfnhn** [comment]
my-bin-log.txt
`# at 3232
#191224 11:38:04 server id 2236393393  end_log_pos 3263 CRC32 0xc2123116        Xid = 23
COMMIT/*!*/;
# at 3263
#191224 11:38:04 server id 2236393393  end_log_pos 3311 CRC32 0x86861a2b        GTID [commit=yes]
SET @@SESSION.GTID_NEXT= '7946dcf1-8638-11e7-836c-7cd30abda78a:4953767'/*!*/;
# at 3311
#191224 11:38:04 server id 2236393393  end_log_pos 3374 CRC32 0xb05fec09        Query   thread_id=6065117       exec_time=0     error_code=0
SET TIMESTAMP=1577158684/*!*/;
BEGIN
/*!*/;
# at 3374
#191224 11:38:04 server id 2236393393  end_log_pos 3505 CRC32 0xd0348d29        Table_map: `ccccccc`.`fffffffff` mapped to number 72
# at 3505
#191224 11:38:04 server id 2236393393  end_log_pos 3753 CRC32 0xf999a2c0        Write_rows: table id 72 flags: STMT_END_F
### INSERT INTO `ccccccc`.`fffffffff`
### SET
###   @1='19122411380405636' /* VARSTRING(63) meta=63 nullable=0 is_null=0 */
###   @2='19082409555401696' /* VARSTRING(90) meta=90 nullable=0 is_null=0 */`

**Comment by v0112358** [comment]
I have the same issue. 
```
Traceback (most recent call last):
  File "/usr/local/bin/mysql-binlog-explorer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/binlogexplorer/webui.py", line 98, in main
    transactions += parser.parse(content)
  File "/usr/local/lib/python2.7/site-packages/binlogexplorer/binlog_parser.py", line 63, in parse
    transaction.end_date = datetime.strptime(last_line[1:16], '%y%m%d %H:%M:%S')
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data 'ET TIMESTAMP=15' does not match format '%y%m%d %H:%M:%S'
```
I am using MySQL 5.7. Could you update this project to support MySQL 5.7 ?

**Comment by israelbgf** [comment]
Hmm, I didn't test it with MySQL 5.7 as I said in the readme. Maybe something is off in this version. But it's quite easy to extend it, I suggest you to get the source code and try to debug what's happening. The tests probably will put you on track. PRs are welcome. :)

@sbwfnhn did you also test it with MySQL 5.7?

(sorry for the late response, somehow I'm not receiving notifications)
